# Copyright (c) Malong Technologies Co., Ltd.
# All rights reserved.
#
# Contact: github@malong.com
#
# This source code is licensed under the LICENSE file in the root directory of this source tree.

MODEL:
  BACKBONE:
    NAME: bninception

# INPUT:
#   MODE: 'RGB'
#   PIXEL_MEAN: [0.485, 0.456, 0.406]
#   PIXEL_STD: [0.229, 0.224, 0.225]

SAVE_DIR: output/bninception-pad-bs256-epochs60

SOLVER:
  MAX_ITERS: 22260
  STEPS: [11130, 18550]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.00001
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 3170
  WEIGHT_DECAY: 0.0005
  CHECKPOINT_PERIOD: 400
  
DATA:
  DATASET_CLASS: "RetailDataset"
  LABEL_MAP_PATH: /data2/datasets/clobotics/embedding/indices/inedailysampling20200706_ccth_r5_png_r6_chinadrink_r7_class_list.txt
  TRAIN_IMG_SOURCE: /data2/datasets/clobotics/embedding/indices/ccth_r5_png_r6_chinadrink_r7.txt
  TEST_QUERY_IMG_SOURCE: /data2/datasets/clobotics/embedding/testsets/ine-daily-sampling-20200706/query.txt
  TEST_GALLERY_IMG_SOURCE: /data2/datasets/clobotics/embedding/testsets/ine-daily-sampling-20200706/gallery_distractor.txt
  TRAIN_BATCHSIZE: 96
  TEST_BATCHSIZE: 256
  NUM_WORKERS: 8
  NUM_INSTANCES: 6
  TRANSFORM:
    PAD_SHORTER: True

VALIDATION:
  VERBOSE: 400